### ISSUE TITLE
Timetable error

### ISSUE THREAD

**Issue by tr-j** [GibbonEdu/core#1395]
**Describe the bug**

After rolling over to the next academic year the timetable is no longer rendering on the home page (Planner).

**To Reproduce**

1. Go to home page - click Planner.

**Expected behavior**

Normally, this syncs with the calendar and shows lessons and timetabled classes in a table.

Now it just shows "Loading" with the spinning loader bar. I can see a 500 error and this is output from the log:

[13-Aug-2021 14:36:41] PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /home/gibbon/public_html/vendor/google/apiclient/src/Google/Service/Resource.php:291
Stack trace:
#0 /home/gibbon/public_html/vendor/google/apiclient/src/Google/Service/Resource.php(291): implode(Array, '&')
#1 /home/gibbon/public_html/vendor/google/apiclient/src/Google/Service/Resource.php(190): Google_Service_Resource->createRequestUri('calendars/{cale...', Array)
#2 /home/gibbon/public_html/vendor/google/apiclient-services/src/Google/Service/Calendar/Resource/Events.php(271): Google_Service_Resource->call('list', Array, 'Google_Service_...')
#3 /home/gibbon/public_html/modules/Timetable/moduleFunctions.php(189): Google_Service_Calendar_Resource_Events->listEvents('SANITIZED', Array)
#4 /home/gibbon/public_html/modules/Timetable/moduleFunctions.php(547): getCalendarEvents(Object(PDO), 'SANITIZED', 'SANITIZED', SANITIZED, SANITIZED)
#5 /home/gibbon/public_html/index_tt_ajax.php(52): renderTT('SANITIZED-...', Object(PDO), '0000000001', '00000004', false, SANITIZED, '', '', 'trim')
#6 {main}
  thrown in /home/gibbon/public_html/vendor/google/apiclient/src/Google/Service/Resource.php on line 291

I've seen this error since upgrading to the newest version of Gibbon and using PHP 8.

I also deleted the Google Calendar link under third party integration to see if it had an effect, but there was no change.

**Your System**

 - Gibbon version v22.0.00

**Comment by yookoala** [comment]
@tr-j: Thanks for reporting. Which PHP version are you using now?

**Comment by yookoala** [comment]
This is a bug in Google API client using legacy signature of [implode()](https://www.php.net/manual/en/function.implode.php):

![2021-08-13 16-34-06 的螢幕擷圖](https://user-images.githubusercontent.com/91274/129329063-9736ba4c-8e35-4a10-af41-c08ad1ac9495.png)

This signature has made obsoleted since PHP 7.4. Google API client has fixed by googleapis/google-api-php-client#1683. Upgrading to [Google API Client v2.2.4](https://github.com/googleapis/google-api-php-client/commits/v2.2.4) or later should fix the issue. If you know how to use [composer](https://getcomposer.org/), please try this command in the Gibbon's root folder:

```
composer require google/apiclient:"^2.2.0"
```

The Google API Client should be updated to 2.4.0. And the fix should be included. Please check.

**Comment by tr-j** [comment]
Thank you - I upgraded the client library with composer and it has partially fixed the problem. There is no error in the log now and the index_tt_ajax.php is no longer returning a 500 error. However, the timetable is blank. When I view the ajax request I see that no parameters are sent with the query:

{
	"gibbonTTID": "",
	"ttDate": "",
	"fromTT": "",
	"personalCalendar": "",
	"schoolCalendar": "",
	"spaceBookingCalendar": ""
}

**Comment by tr-j** [comment]
After a further look, it does not appear the blank parameters is causing the error. First, when I open the home page it defaults to the "Staff Information" tab instead of the "Planner". Second, when I click on the "Last Week" or "First Week" it does submit the form through Ajax with data, but it still comes back blank. If I click "This Week" then it appears to post the page and comes back on the "Staff Information" tab (but the timetable is still empty).

There are no errors in the javascript console, browser network logs, or PHP error log.

Oddly, if I cycle back in the calendar ("Last week") to the point that our school was closed then the calendar starts to work and shows the school closed and properly imports my personal calendar.

**Comment by yookoala** [comment]
@tr-j: I think this is a different error than the one you reported before. Could you please open another issue for this? Thanks.

**Comment by tr-j** [comment]
The issue is resolved with the updated libraries. Our other issue was a configuration error and everything is now working properly.
